import { v4 as uuidv4 } from "uuid"

export const listCoffee = [
  {
    id: uuidv4(),
    name: "Expresso Tradicional",
    price: "9,99",
    image: "https://i.imgur.com/mrRlRAh.png",
    type: ["Tradicional"],
  },
  {
    id: uuidv4(),
    name: "Expresso Americano",
    price: "9,99",
    image: "https://i.imgur.com/md3PdOU.png",
    type: ["Tradicional"],
  },
  {
    id: uuidv4(),
    name: "Expresso Cremoso",
    price: "9,99",
    image: "https://i.imgur.com/M5v0L87.png",
    type: ["Tradicional"],
  },
  {
    id: uuidv4(),
    name: "Expresso Gelado",
    price: "9,99",
    image: "https://i.imgur.com/imAlpw6.png",
    type: ["Tradicional", "Gelado"],
  },
  {
    id: uuidv4(),
    name: "Café com Leite",
    price: "9,99",
    image: "https://i.imgur.com/x9bMRcQ.png",
    type: ["Tradicional", "Com leite"],
  },
  {
    id: uuidv4(),
    name: "Latte",
    price: "9,99",
    image: "https://i.imgur.com/ogWRSbP.png",
    type: ["Tradicional", "Com leite"],
  },
  {
    id: uuidv4(),
    name: "Capuccino",
    price: "9,99",
    image: "https://i.imgur.com/EXOugBe.png",
    type: ["Tradicional", "Com leite"],
  },
  {
    id: uuidv4(),
    name: "Macchiato",
    price: "9,99",
    image: "https://i.imgur.com/PELy2UP.png",
    type: ["Tradicional", "Com leite"],
  },
  {
    id: uuidv4(),
    name: "Mocaccino",
    price: "9,99",
    image: "https://i.imgur.com/XVYUpoZ.png",
    type: ["Tradicional", "Com leite"],
  },
  {
    id: uuidv4(),
    name: "Chocolate Quente",
    price: "9,99",
    image: "https://i.imgur.com/Nji4Suo.png",
    type: ["Especial", "Com leite"],
  },
  {
    id: uuidv4(),
    name: "Cubano",
    price: "9,99",
    image: "https://i.imgur.com/r2OSTST.png",
    type: ["Especial", "Alcoólico", "Gelado"],
  },
  {
    id: uuidv4(),
    name: "Havaiano",
    price: "9,99",
    image: "https://i.imgur.com/B3LvKlD.png",
    type: ["Especial"],
  },
  {
    id: uuidv4(),
    name: "Árabe",
    price: "9,99",
    image: "https://i.imgur.com/RNB7EuI.png",
    type: ["Especial"],
  },
  {
    id: uuidv4(),
    name: "Irlandês",
    price: "9,99",
    image: "https://i.imgur.com/GesgK2k.png",
    type: ["Especial", "Alcoólico"],
  },
]
